# Uncomment this line to define a global platform for your project
platform :ios, '7.1'

pod 'RSImageLoader', :path => '../RSImageLoader.podspec'

target 'RSImageLoaderExample' do

end

target 'RSImageLoaderExampleTests' do

end

